Blog app: add devise
Ntwali-Josue/Blog-app pull request #8
Opened 2022-03-01 18:29 UTC by Ntwali-Josue

2022-03-01 21:35 UTC, julie-ify requested changes
## Hi @Ntwali-Josue,

Good job so far!

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Good code organization ✔️
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

- [ ] **[REQUIRED]** Kindly add instructions on how to set up your database in the README. Something like `rails db:create`, `rails db:migrate` and `rails db:seed` if you have any data in the seed file

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-01 21:35 UTC, julie-ify commented on app/controllers/application_controller.rb
> +    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :bio, :password) }
- [ ]  I suggest you include `password_confirmation` as one of the permitted parameters for `sign_up` because I received this error below while signing up;

<img width="390" alt="Code_2ebHVfEjTG" src="https://user-images.githubusercontent.com/81468675/156250833-a75b4a67-15e2-440a-9f6a-a09093893c8b.png">

2022-03-01 21:35 UTC, julie-ify commented on app/controllers/application_controller.rb
>  end
- [ ] I was able to see the index page of your application without being authenticated i.e without signing up or login in. However, the reason for adding devise is for user authentication so that a user can sign up and login before having access to our application. Kindly fix this by adding `before_action :authenticate_user!` after line 2 in this `application_controller` to fix this issue. You will see that after adding the `before_action :authenticate_user!`, a new user must be taken to the sign_in or sign_up page to get authenticated before having access to the application.

2022-03-01 21:35 UTC, julie-ify commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable, :confirmable
- [ ] The email confirmation works well. Keep rocking 👍

2022-03-01 21:35 UTC, julie-ify commented on app/views/devise/registrations/new.html.erb
> +<%= render "devise/shared/links" %>
- [ ]  Kindly modify the views in devise for the registration and login to match the provided wireframe.

Your Implementation | Wireframe
:---:|:---:
![](https://i.imgur.com/sYq3iYr.png) | ![](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_login.png)

2022-03-02 12:52 UTC, t-yanick approved these changes
Hi @Ntwali-Josue, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-02 15:29 UTC, merged